# Generated by Django 4.2.5 on 2023-10-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fist_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=40)),
                ('course', models.CharField(max_length=50)),
                ('fee', models.IntegerField()),
                ('assigment1', models.IntegerField()),
                ('assigment2', models.IntegerField()),
                ('assigment3', models.IntegerField()),
                ('assigment4', models.IntegerField()),
                ('institute', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
